apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-prometheus
spec:
  replicas: {{ .Values.prometheus.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-prometheus
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-prometheus
    spec:
      serviceAccountName: {{ .Release.Name }}-prometheus
      containers:
        - name: {{ .Release.Name }}-prometheus
          image: {{ .Values.prometheus.container.image }}
          volumeMounts:
          - name: config-volume
            mountPath: /etc/prometheus/
          args:
          - '--config.file=/etc/prometheus/prometheus.yml'
          ports:
          - containerPort: {{ .Values.prometheus.container.portPod }}

      volumes:  #ะะท ConfigMap
      - name: config-volume
        configMap:
          name: {{ .Release.Name }}-prometheus-config