apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-prometheus-service
spec:
  selector:
    app: {{ .Release.Name }}-prometheus
  ports:
    - name:
      protocol: TCP
      port: {{ .Values.prometheus.container.portPod}}
      targetPort: {{ .Values.prometheus.container.portIn}}
  type: ClusterIP