// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mock_httptests is a generated GoMock package.
package mock_httptests

import (
	context "context"
	g_serv "grpc/pkg/proto"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockHTTPServer is a mock of HTTPServer interface.
type MockHTTPServer struct {
	ctrl     *gomock.Controller
	recorder *MockHTTPServerMockRecorder
}

// MockHTTPServerMockRecorder is the mock recorder for MockHTTPServer.
type MockHTTPServerMockRecorder struct {
	mock *MockHTTPServer
}

// NewMockHTTPServer creates a new mock instance.
func NewMockHTTPServer(ctrl *gomock.Controller) *MockHTTPServer {
	mock := &MockHTTPServer{ctrl: ctrl}
	mock.recorder = &MockHTTPServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHTTPServer) EXPECT() *MockHTTPServerMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockHTTPServer) Get(ctx context.Context, requestData *g_serv.GetRequest, opts ...grpc.CallOption) (*g_serv.GetResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, requestData}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Get", varargs...)
	ret0, _ := ret[0].(*g_serv.GetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockHTTPServerMockRecorder) Get(ctx, requestData interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, requestData}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockHTTPServer)(nil).Get), varargs...)
}

// Post mocks base method.
func (m *MockHTTPServer) Post(ctx context.Context, requestData *g_serv.PostRequest, opts ...grpc.CallOption) (*g_serv.PostResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, requestData}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Post", varargs...)
	ret0, _ := ret[0].(*g_serv.PostResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Post indicates an expected call of Post.
func (mr *MockHTTPServerMockRecorder) Post(ctx, requestData interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, requestData}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Post", reflect.TypeOf((*MockHTTPServer)(nil).Post), varargs...)
}

// MockHttpRequestGrpc is a mock of HttpRequestGrpc interface.
type MockHttpRequestGrpc struct {
	ctrl     *gomock.Controller
	recorder *MockHttpRequestGrpcMockRecorder
}

// MockHttpRequestGrpcMockRecorder is the mock recorder for MockHttpRequestGrpc.
type MockHttpRequestGrpcMockRecorder struct {
	mock *MockHttpRequestGrpc
}

// NewMockHttpRequestGrpc creates a new mock instance.
func NewMockHttpRequestGrpc(ctrl *gomock.Controller) *MockHttpRequestGrpc {
	mock := &MockHttpRequestGrpc{ctrl: ctrl}
	mock.recorder = &MockHttpRequestGrpcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHttpRequestGrpc) EXPECT() *MockHttpRequestGrpcMockRecorder {
	return m.recorder
}

// GetRequestGrpc mocks base method.
func (m *MockHttpRequestGrpc) GetRequestGrpc(ctx context.Context, requestData *g_serv.GetRequest) (*g_serv.GetResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequestGrpc", ctx, requestData)
	ret0, _ := ret[0].(*g_serv.GetResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRequestGrpc indicates an expected call of GetRequestGrpc.
func (mr *MockHttpRequestGrpcMockRecorder) GetRequestGrpc(ctx, requestData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequestGrpc", reflect.TypeOf((*MockHttpRequestGrpc)(nil).GetRequestGrpc), ctx, requestData)
}

// PostRequestGrpc mocks base method.
func (m *MockHttpRequestGrpc) PostRequestGrpc(ctx context.Context, requestData *g_serv.PostRequest) (*g_serv.PostResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostRequestGrpc", ctx, requestData)
	ret0, _ := ret[0].(*g_serv.PostResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PostRequestGrpc indicates an expected call of PostRequestGrpc.
func (mr *MockHttpRequestGrpcMockRecorder) PostRequestGrpc(ctx, requestData interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostRequestGrpc", reflect.TypeOf((*MockHttpRequestGrpc)(nil).PostRequestGrpc), ctx, requestData)
}
