stages:
  - test
  - build
  - deploy


test-job:
  stage: test
  image: golang:1.25.1-alpine3.22
  script:
    - go test ./...

build-job:
  stage: build
  script:
    - docker build -t grpc_server -f Dockerfile.gRPC_server .
    - docker build -t http_server -f Dockerfile.http_server .

deploy-job:
  stage: deploy
  environment: production
  script:
    - docker compose up -d