FROM golang:1.25.1-alpine3.22

WORKDIR /app


COPY . .
RUN go mod download

RUN go build -o gRPC-server ./cmd/gRPC_server/gRPCserver.go
RUN chmod +x gRPC-server

EXPOSE 8090

CMD ["./gRPC-server", "--config=./config/local.yml"]

#docker build -t grpc_server -f Dockerfile.gRPC_server .