FROM golang:1.25.1-alpine3.22

WORKDIR /app


COPY . .
RUN go mod download

RUN go build -o http-server ./cmd/client/httpServer.go
RUN chmod +x http-server

EXPOSE 8080

CMD ["./http-server", "--config=./config/local.yml"]

#docker build -t http_server -f Dockerfile.http_server .