version: "3"
tasks:
    generate: 
        aliases: 
            - gen
        desc: "Generate code from proto files"
        cmds: 
            - protoc api/service/service.proto --go_out=. --go-grpc_out=. 