global:
  scrape_interval: 3s
  evaluation_interval: 3s

scrape_configs:
  - job_name: "http-server"
    scrape_interval: 3s
    scrape_timeout: 3s
    metrics_path: /metrics
    static_configs:
      - targets: ["http-server:8081"]