env: "development" #production
database:
  username: "postgres"
  password: "1234"
  host: "postgres"
  port: 5432
  db_name: "miniGRPC"

grpc_server:
  port: 8090
  host: "0.0.0.0" #grpc-server

http_server:
  port: 8080
  host: "0.0.0.0"
