env: "development" #production
database:
  username: "postgres"
  password: "1234"
  host: "localhost"
  port: 5432
  db_name: "miniGRPC"

grpc_server:
  port: 8090
  host: "localhost"

http_server:
  port: 8080
  host: "localhost"
  grpc_client:
    port: 8090
    host: "localhost"