apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-grafana
spec:
  replicas: {{ .Values.grafana.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-grafana
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-grafana
    spec:
      containers:
      - name: {{ .Release.Name }}-grafana
        image: {{ .Values.grafana.container.image }}
        env:
        - name: GF_SECURITY_ADMIN_USER
          value: {{ .Values.grafana.container.admin_user }}
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: {{ .Values.grafana.container.admin_pass }}
        volumeMounts:
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
        ports:
        - containerPort: {{ .Values.grafana.container.portPod }}
      volumes:
      - name: grafana-datasources
        configMap:
          name: {{ .Release.Name }}-grafana-datasources